/**
 * PDF Export Service for LegalNexus Reports
 * Generates professional PDF reports with branding
 */

import PDFDocument from 'pdfkit';
import { Response } from 'express';

// LegalNexus brand colors
const COLORS = {
  primary: '#2c3e50',
  accent: '#f39c12',
  secondary: '#34495e',
  text: '#333333',
  lightGray: '#ecf0f1',
  success: '#28a745',
  warning: '#ff9800',
  danger: '#dc3545',
};

export class PDFExportService {
  /**
   * Create a new PDF document with LegalNexus branding
   */
  private static createDocument(): PDFDocument {
    return new PDFDocument({
      size: 'A4',
      margins: {
        top: 50,
        bottom: 50,
        left: 50,
        right: 50,
      },
      info: {
        Title: 'LegalNexus Report',
        Author: 'LegalNexus Enterprise',
        Subject: 'Practice Intelligence Report',
        Creator: 'Vicktoria AI',
      },
    });
  }

  /**
   * Add LegalNexus header to PDF
   */
  private static addHeader(doc: PDFDocument, title: string, firmName?: string) {
    // Header background
    doc
      .rect(0, 0, doc.page.width, 80)
      .fill(COLORS.primary);

    // LegalNexus logo/title
    doc
      .fontSize(24)
      .fillColor('#ffffff')
      .font('Helvetica-Bold')
      .text('LegalNexus', 50, 25);

    doc
      .fontSize(10)
      .fillColor(COLORS.accent)
      .font('Helvetica')
      .text('Soul Logic Powered', 50, 52);

    // Report title
    doc
      .fontSize(16)
      .fillColor('#ffffff')
      .font('Helvetica-Bold')
      .text(title, 250, 30, { align: 'right', width: 300 });

    // Firm name and date
    if (firmName) {
      doc
        .fontSize(9)
        .fillColor(COLORS.lightGray)
        .font('Helvetica')
        .text(firmName, 250, 52, { align: 'right', width: 300 });
    }

    doc
      .fontSize(9)
      .fillColor(COLORS.lightGray)
      .text(new Date().toLocaleDateString('en-ZA'), 250, 64, { align: 'right', width: 300 });

    doc.moveDown(5);
  }

  /**
   * Add footer to PDF
   */
  private static addFooter(doc: PDFDocument, pageNumber: number) {
    doc
      .fontSize(9)
      .fillColor(COLORS.text)
      .font('Helvetica')
      .text(
        `Page ${pageNumber} | Generated by Vicktoria AI | ${new Date().toLocaleString('en-ZA')}`,
        50,
        doc.page.height - 50,
        { align: 'center', width: doc.page.width - 100 }
      );
  }

  /**
   * Export Fee Earner Rankings Report
   */
  static async exportFeeEarnerRankings(
    res: Response,
    data: any[],
    meta: any,
    firmName?: string
  ): Promise<void> {
    const doc = this.createDocument();

    // Set response headers
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="fee-earner-rankings-${Date.now()}.pdf"`);

    // Pipe to response
    doc.pipe(res);

    // Add header
    this.addHeader(doc, 'Fee Earner Rankings Report', firmName);

    // Summary section
    doc
      .fontSize(14)
      .fillColor(COLORS.primary)
      .font('Helvetica-Bold')
      .text('Summary', 50, 120);

    const totalRevenue = data.reduce((sum, e) => sum + parseFloat(e.total_revenue || 0), 0);
    const totalHours = data.reduce((sum, e) => sum + parseFloat(e.total_hours || 0), 0);

    doc
      .fontSize(10)
      .fillColor(COLORS.text)
      .font('Helvetica')
      .text(`Period: ${meta.period}`, 50, 145)
      .text(`Total Attorneys: ${meta.total_attorneys}`, 50, 160)
      .text(`Total Revenue: R ${totalRevenue.toLocaleString('en-ZA', { minimumFractionDigits: 2 })}`, 50, 175)
      .text(`Total Hours: ${totalHours.toFixed(2)}`, 50, 190)
      .moveDown(2);

    // Rankings table
    doc
      .fontSize(14)
      .fillColor(COLORS.primary)
      .font('Helvetica-Bold')
      .text('Attorney Rankings', 50, 230);

    // Table headers
    const tableTop = 260;
    doc
      .fontSize(9)
      .fillColor('#ffffff')
      .font('Helvetica-Bold');

    doc.rect(50, tableTop, 495, 25).fill(COLORS.secondary);

    doc
      .fillColor('#ffffff')
      .text('Rank', 60, tableTop + 8, { width: 40 })
      .text('Attorney', 110, tableTop + 8, { width: 120 })
      .text('Department', 240, tableTop + 8, { width: 80 })
      .text('Hours', 330, tableTop + 8, { width: 50 })
      .text('Revenue', 390, tableTop + 8, { width: 80, align: 'right' })
      .text('Matters', 480, tableTop + 8, { width: 55, align: 'right' });

    // Table rows
    let y = tableTop + 35;
    doc.fontSize(9).font('Helvetica');

    data.forEach((attorney, index) => {
      if (y > 750) {
        // Add footer before new page
        this.addFooter(doc, 1);
        doc.addPage();
        this.addHeader(doc, 'Fee Earner Rankings Report (continued)', firmName);
        y = 120;
      }

      const bgColor = index % 2 === 0 ? '#ffffff' : COLORS.lightGray;
      doc.rect(50, y - 5, 495, 20).fill(bgColor);

      const rankColor = index === 0 ? '#FFD700' : index === 1 ? '#C0C0C0' : index === 2 ? '#CD7F32' : COLORS.text;
      doc
        .fillColor(rankColor)
        .font('Helvetica-Bold')
        .text(`#${attorney.rank}`, 60, y, { width: 40 });

      doc
        .fillColor(COLORS.text)
        .font('Helvetica')
        .text(attorney.name, 110, y, { width: 120 })
        .text(attorney.department || 'N/A', 240, y, { width: 80 })
        .text(parseFloat(attorney.total_hours).toFixed(2), 330, y, { width: 50 })
        .text(`R ${parseFloat(attorney.total_revenue).toLocaleString('en-ZA')}`, 390, y, { width: 80, align: 'right' })
        .text(attorney.matters_count.toString(), 480, y, { width: 55, align: 'right' });

      y += 20;
    });

    // Add footer
    this.addFooter(doc, 1);

    // Finalize PDF
    doc.end();
  }

  /**
   * Export Practice Area Analytics Report
   */
  static async exportPracticeAreaAnalytics(
    res: Response,
    data: any[],
    meta: any,
    firmName?: string
  ): Promise<void> {
    const doc = this.createDocument();

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="practice-area-analytics-${Date.now()}.pdf"`);

    doc.pipe(res);
    this.addHeader(doc, 'Practice Area Analytics Report', firmName);

    // Summary
    doc
      .fontSize(14)
      .fillColor(COLORS.primary)
      .font('Helvetica-Bold')
      .text('Summary', 50, 120);

    const totalRevenue = data.reduce((sum, d) => sum + parseFloat(d.total_revenue || 0), 0);
    const totalHours = data.reduce((sum, d) => sum + parseFloat(d.total_hours || 0), 0);

    doc
      .fontSize(10)
      .fillColor(COLORS.text)
      .font('Helvetica')
      .text(`Period: ${meta.period}`, 50, 145)
      .text(`Total Departments: ${meta.total_departments || data.length}`, 50, 160)
      .text(`Total Revenue: R ${totalRevenue.toLocaleString('en-ZA', { minimumFractionDigits: 2 })}`, 50, 175)
      .text(`Total Hours: ${totalHours.toFixed(2)}`, 50, 190);

    // Department breakdown
    doc
      .fontSize(14)
      .fillColor(COLORS.primary)
      .font('Helvetica-Bold')
      .text('Department Performance', 50, 230);

    let y = 260;
    data.forEach((dept, index) => {
      if (y > 700) {
        this.addFooter(doc, 1);
        doc.addPage();
        this.addHeader(doc, 'Practice Area Analytics (continued)', firmName);
        y = 120;
      }

      // Department card
      doc.rect(50, y, 495, 80).fill(COLORS.lightGray);

      doc
        .fontSize(12)
        .fillColor(COLORS.primary)
        .font('Helvetica-Bold')
        .text(dept.department, 60, y + 10);

      doc
        .fontSize(10)
        .fillColor(COLORS.text)
        .font('Helvetica')
        .text(`Revenue: R ${parseFloat(dept.total_revenue).toLocaleString('en-ZA')}`, 60, y + 30)
        .text(`Hours: ${parseFloat(dept.total_hours).toFixed(2)}`, 60, y + 45)
        .text(`Matters: ${dept.matters_count}`, 60, y + 60);

      const avgValue = parseFloat(dept.total_revenue) / parseInt(dept.matters_count);
      doc.text(`Avg Matter Value: R ${avgValue.toLocaleString('en-ZA')}`, 300, y + 30);

      y += 90;
    });

    this.addFooter(doc, 1);
    doc.end();
  }

  /**
   * Export Billing Inertia Report
   */
  static async exportBillingInertia(
    res: Response,
    data: any[],
    meta: any,
    firmName?: string
  ): Promise<void> {
    const doc = this.createDocument();

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="billing-inertia-${Date.now()}.pdf"`);

    doc.pipe(res);
    this.addHeader(doc, 'Billing Inertia Report', firmName);

    // Alert banner
    if (data.length > 0) {
      doc.rect(50, 120, 495, 40).fill('#fff3cd');
      doc
        .fontSize(12)
        .fillColor('#856404')
        .font('Helvetica-Bold')
        .text('⚠️ REVENUE AT RISK', 60, 130);

      const totalAtRisk = data.reduce((sum, a) => sum + parseFloat(a.unbilled_amount || 0), 0);
      doc
        .fontSize(10)
        .font('Helvetica')
        .text(`R ${totalAtRisk.toLocaleString('en-ZA')} in unbilled revenue detected`, 60, 147);
    }

    // Summary
    const totalUnbilled = data.reduce((sum, a) => sum + parseFloat(a.unbilled_amount || 0), 0);
    const totalHours = data.reduce((sum, a) => sum + parseFloat(a.unbilled_hours || 0), 0);

    doc
      .fontSize(14)
      .fillColor(COLORS.primary)
      .font('Helvetica-Bold')
      .text('Summary', 50, 180);

    doc
      .fontSize(10)
      .fillColor(COLORS.text)
      .font('Helvetica')
      .text(`Attorneys with Inertia: ${meta.total_attorneys || data.length}`, 50, 205)
      .text(`Total Unbilled Revenue: R ${totalUnbilled.toLocaleString('en-ZA')}`, 50, 220)
      .text(`Total Unbilled Hours: ${totalHours.toFixed(2)}`, 50, 235);

    // Inertia details
    doc
      .fontSize(14)
      .fillColor(COLORS.primary)
      .font('Helvetica-Bold')
      .text('Inertia Breakdown', 50, 270);

    let y = 300;
    data.forEach((attorney, index) => {
      if (y > 720) {
        this.addFooter(doc, 1);
        doc.addPage();
        this.addHeader(doc, 'Billing Inertia (continued)', firmName);
        y = 120;
      }

      const score = parseInt(attorney.inertia_score);
      const severity = score >= 75 ? COLORS.danger : score >= 50 ? COLORS.warning : COLORS.success;

      doc.rect(50, y, 495, 60).fill(COLORS.lightGray);

      doc
        .fontSize(11)
        .fillColor(COLORS.primary)
        .font('Helvetica-Bold')
        .text(attorney.name, 60, y + 10);

      doc
        .fontSize(10)
        .fillColor(severity)
        .font('Helvetica-Bold')
        .text(`Inertia Score: ${score}`, 350, y + 10);

      doc
        .fontSize(9)
        .fillColor(COLORS.text)
        .font('Helvetica')
        .text(`Unbilled Revenue: R ${parseFloat(attorney.unbilled_amount).toLocaleString('en-ZA')}`, 60, y + 28)
        .text(`Unbilled Hours: ${parseFloat(attorney.unbilled_hours).toFixed(2)}`, 60, y + 42)
        .text(`Days Overdue: ${attorney.days_overdue}`, 300, y + 28)
        .text(`Oldest Entry: ${new Date(attorney.oldest_unbilled_date).toLocaleDateString('en-ZA')}`, 300, y + 42);

      y += 70;
    });

    this.addFooter(doc, 1);
    doc.end();
  }

  /**
   * Export Executive Summary Report
   */
  static async exportExecutiveSummary(
    res: Response,
    data: any,
    firmName?: string
  ): Promise<void> {
    const doc = this.createDocument();

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="executive-summary-${Date.now()}.pdf"`);

    doc.pipe(res);
    this.addHeader(doc, 'Executive Summary - Soul Logic Report', firmName);

    // Soul Logic Score (large, centered)
    const score = data.soulLogicScore || 0;
    const scoreColor = score >= 80 ? COLORS.success : score >= 60 ? COLORS.warning : COLORS.danger;

    doc
      .fontSize(48)
      .fillColor(scoreColor)
      .font('Helvetica-Bold')
      .text(score.toString(), 50, 140, { align: 'center', width: 495 });

    doc
      .fontSize(14)
      .fillColor(COLORS.primary)
      .font('Helvetica')
      .text('Soul Logic Score', 50, 200, { align: 'center', width: 495 });

    // Metrics grid
    doc
      .fontSize(14)
      .fillColor(COLORS.primary)
      .font('Helvetica-Bold')
      .text('Firm Metrics (Last 30 Days)', 50, 250);

    if (data.metrics) {
      const metrics = [
        { label: 'Total Revenue', value: `R ${parseFloat(data.metrics.totalRevenue || 0).toLocaleString('en-ZA')}` },
        { label: 'Billable Hours', value: data.metrics.billableHours || 0 },
        { label: 'Average Utilization', value: `${data.metrics.averageUtilization || 0}%` },
        { label: 'Unbilled Revenue at Risk', value: `R ${parseFloat(data.metrics.unbilledRevenueAtRisk || 0).toLocaleString('en-ZA')}` },
      ];

      let y = 280;
      metrics.forEach((metric, index) => {
        const x = index % 2 === 0 ? 50 : 300;
        if (index > 0 && index % 2 === 0) y += 50;

        doc.rect(x, y, 230, 40).fill(COLORS.lightGray);
        doc
          .fontSize(9)
          .fillColor(COLORS.text)
          .font('Helvetica')
          .text(metric.label, x + 10, y + 10);
        doc
          .fontSize(12)
          .fillColor(COLORS.primary)
          .font('Helvetica-Bold')
          .text(metric.value, x + 10, y + 24);
      });
    }

    // Energy Drains
    if (data.energyDrains && data.energyDrains.length > 0) {
      doc
        .fontSize(14)
        .fillColor(COLORS.danger)
        .font('Helvetica-Bold')
        .text('⚠️ Energy Drains Detected', 50, 430);

      let y = 460;
      data.energyDrains.forEach((drain: any) => {
        const severityColor = drain.severity === 'high' ? COLORS.danger : drain.severity === 'medium' ? COLORS.warning : COLORS.success;

        doc
          .fontSize(10)
          .fillColor(severityColor)
          .font('Helvetica-Bold')
          .text(`• ${drain.type}`, 60, y);

        doc
          .fontSize(9)
          .fillColor(COLORS.text)
          .font('Helvetica')
          .text(drain.description, 70, y + 15, { width: 460 });

        y += 45;
      });
    } else {
      doc
        .fontSize(12)
        .fillColor(COLORS.success)
        .font('Helvetica-Bold')
        .text('✓ No Energy Drains - Firm Operating Optimally', 50, 430);
    }

    this.addFooter(doc, 1);
    doc.end();
  }
}
